#!/usr/bin/env python3
"""
Generate improved da65 .info files using reachability analysis.

Runs the reachability tracer on each bank, then writes RANGE directives:
  - Unreachable regions → ByteTable (data)
  - Reachable regions → Code (left for da65 to disassemble as instructions)

Also handles the 6-byte interrupt vector region at $FFFA-$FFFF in bank $0F
as a WordTable (AddrTable).
"""

import os
import sys

# Import reachability tracer
sys.path.insert(0, os.path.dirname(__file__))
from reachability import trace_reachability, OPCODES

BANK_SIZE = 0x4000
NUM_BANKS = 16


def find_contiguous_regions(mask, target_val):
    """Find contiguous runs of target_val in a bytearray. Returns [(start, end), ...]."""
    regions = []
    start = None
    for i, b in enumerate(mask):
        if b == target_val:
            if start is None:
                start = i
        else:
            if start is not None:
                regions.append((start, i - 1))
                start = None
    if start is not None:
        regions.append((start, len(mask) - 1))
    return regions


def merge_small_gaps(regions, min_gap=2):
    """Merge data regions separated by tiny gaps (1-2 bytes likely aren't real code)."""
    if not regions:
        return regions
    merged = [regions[0]]
    for start, end in regions[1:]:
        prev_start, prev_end = merged[-1]
        if start - prev_end <= min_gap:
            merged[-1] = (prev_start, end)
        else:
            merged.append((start, end))
    return merged


def generate_info(bank_num):
    """Generate an improved .info file for one bank."""
    hex_str = f'{bank_num:02X}'
    bin_path = f'build/bank{hex_str}.bin'
    info_path = f'build/bank{hex_str}.info'
    base_addr = 0xC000 if bank_num == 0x0F else 0x8000

    with open(bin_path, 'rb') as f:
        bin_data = f.read()

    # Run reachability analysis
    reached = trace_reachability(bin_data, base_addr)

    # Find unreachable (data) regions
    data_regions = find_contiguous_regions(reached, ord('.'))

    # Merge regions separated by tiny gaps (1-2 byte "code" between data blocks
    # is almost certainly data too — the tracer may have resolved a stale pointer)
    data_regions = merge_small_gaps(data_regions, min_gap=2)

    # For bank $0F: ensure vectors at $FFFA-$FFFF are treated as an addr table
    vectors_range = None
    if bank_num == 0x0F:
        vectors_range = (0x3FFA, 0x3FFF)  # offset within bank

    # Write info file
    with open(info_path, 'w') as f:
        f.write(f'# da65 info file for bank ${hex_str}\n')
        f.write(f'# Auto-generated by gen_info_files.py (reachability-based)\n\n')
        f.write(f'GLOBAL {{\n')
        f.write(f'    STARTADDR ${base_addr:04X};\n')
        f.write(f'    INPUTOFFS 0;\n')
        f.write(f'    INPUTSIZE ${BANK_SIZE:04X};\n')
        f.write(f'    CPU "6502";\n')
        f.write(f'}};\n\n')

        # Write data ranges
        data_byte_count = 0
        for rstart, rend in data_regions:
            addr_start = base_addr + rstart
            addr_end = base_addr + rend
            size = rend - rstart + 1
            data_byte_count += size

            # Skip the vector region (handled separately)
            if vectors_range and rstart <= vectors_range[1] and rend >= vectors_range[0]:
                # Split around vector region
                if rstart < vectors_range[0]:
                    f.write(f'RANGE {{ START ${base_addr + rstart:04X}; END ${base_addr + vectors_range[0] - 1:04X}; TYPE ByteTable; }};\n')
                if rend > vectors_range[1]:
                    f.write(f'RANGE {{ START ${base_addr + vectors_range[1] + 1:04X}; END ${addr_end:04X}; TYPE ByteTable; }};\n')
                continue

            f.write(f'RANGE {{ START ${addr_start:04X}; END ${addr_end:04X}; TYPE ByteTable; }};\n')

        # Vector table
        if vectors_range:
            f.write(f'\n# Interrupt vectors\n')
            f.write(f'RANGE {{ START $FFFA; END $FFFF; TYPE AddrTable; }};\n')

        code_byte_count = BANK_SIZE - data_byte_count
        print(f'  Bank ${hex_str}: {len(data_regions)} data regions '
              f'({data_byte_count} bytes data, {code_byte_count} bytes code)')

    return data_regions


def main():
    print("Generating improved da65 info files...")
    print()

    total_data = 0
    total_code = 0

    for bank_num in range(NUM_BANKS):
        hex_str = f'{bank_num:02X}'
        bin_path = f'build/bank{hex_str}.bin'
        if not os.path.exists(bin_path):
            print(f'  Bank ${hex_str}: SKIP (no .bin file)')
            continue

        regions = generate_info(bank_num)
        data_bytes = sum(e - s + 1 for s, e in regions)
        total_data += data_bytes
        total_code += BANK_SIZE - data_bytes

    print()
    print(f'Total: {total_data} bytes data, {total_code} bytes code '
          f'({total_data * 100 / (NUM_BANKS * BANK_SIZE):.1f}% data)')
    print(f'Info files written to build/*.info')


if __name__ == '__main__':
    main()
